sudo: false

notifications:
    email: true

language: node_js

cache:
    directories:
        - node_modules

branches:
    only:
        - master

node_js:
    - "10"

script:
    - npm run lint
    - npm run test:cover

after_success:
    - npm run report-coverage
