sudo: false

notifications:
    email: false

language: node_js

cache:
    directories:
        - node_modules

node_js:
    - "10"

script:
    - npm test

after_success:
    - npm run test:coveralls
